# Generated by Django 3.1 on 2020-08-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200810_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='review',
            name='location',
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
